# Generated by cucumber-sinatra. (Thu Feb 16 22:50:42 -0600 2012)

ENV['RACK_ENV'] = 'test'

PADRINO_ENV = 'test' unless defined?(PADRINO_ENV)

require File.expand_path(File.dirname(__FILE__) + "/../../config/boot")
require File.join(File.dirname(__FILE__), '..', '..', 'app/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = EnovaPoker

class EnovaPokerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  EnovaPokerWorld.new
end
